version: '3'
services:
  mysql:
    image: mysql:5.7.20
    ports:
      - 3306:3306
    volumes:
      - ./Tests/Application/var/data/mysql:/var/lib/mysql:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  elasticsearch:
    image: elasticsearch:6.5.4
    ports:
      - 9200:9200
    volumes:
      - ./Tests/Application/var/data/elasticsearch:/usr/share/elasticsearch/data:cached
    environment:
        ES_JAVA_OPTS: "-Xms750m -Xmx750m"
